#!/usr/bin/env python3
"""
catalog.py — Vulnerability catalogue, known CVEs, mitigations, and fortify mapping.

Expanded with additional dangerous functions, more CVEs, and better categorization
to minimize false positives while maximizing coverage.
"""

# ── Vulnerability catalogue ───────────────────────────────────────────────────
# risk_tier: "always"    = always dangerous if present (no safe use)
#            "context"   = dangerous only if user data reaches it
#            "safe_variant" = safer alternative, low priority informational
# fortify:   maps to _chk symbol name — if FORTIFY present, downgrade severity

VULN_CATALOG = {
    # ─── ALWAYS DANGEROUS (no legitimate safe use) ─────────────────────────────
    "gets":     {"cat": "BufferOverflow",  "cwe": "CWE-120", "cvss": 9.8,
                 "tier": "always", "fortify": "__gets_chk",
                 "desc": "Unbounded stack buffer overflow via gets()"},
    "system":   {"cat": "CommandInjection","cwe": "CWE-78",  "cvss": 9.8,
                 "tier": "always", "fortify": None,
                 "desc": "system() call — OS command injection if input reaches it"},
    "popen":    {"cat": "CommandInjection","cwe": "CWE-78",  "cvss": 9.8,
                 "tier": "always", "fortify": None,
                 "desc": "popen() — OS command injection via shell metacharacters"},
    "wordexp":  {"cat": "CommandInjection","cwe": "CWE-78",  "cvss": 9.8,
                 "tier": "always", "fortify": None,
                 "desc": "wordexp() — command expansion / injection (performs shell expansion)"},
    "tempnam":  {"cat": "InsecureTempFile", "cwe": "CWE-377","cvss": 5.5,
                 "tier": "always", "fortify": None,
                 "desc": "tempnam() — predictable temp file name → race condition / symlink attack"},
    "mktemp":   {"cat": "InsecureTempFile", "cwe": "CWE-377","cvss": 6.5,
                 "tier": "always", "fortify": None,
                 "desc": "mktemp() — predictable temp file → TOCTOU race condition"},
    "tmpnam":   {"cat": "InsecureTempFile", "cwe": "CWE-377","cvss": 5.5,
                 "tier": "always", "fortify": None,
                 "desc": "tmpnam() — predictable temp file name → race condition"},
    "getservbyname": {"cat": "InfoLeak",  "cwe": "CWE-200", "cvss": 5.3,
                 "tier": "always", "fortify": None,
                 "desc": "getservbyname() — may leak service information"},
    "vfork":    {"cat": "RaceCondition",   "cwe": "CWE-362", "cvss": 8.8,
                 "tier": "always", "fortify": None,
                 "desc": "vfork() — parent blocking, stack sharing with child → race condition / code exec"},
    "cuserid":  {"cat": "InfoLeak",      "cwe": "CWE-200", "cvss": 4.3,
                 "tier": "always", "fortify": None,
                 "desc": "cuserid() — leaks username, buffer overflow risk"},
    "crypt":    {"cat": "WeakCrypto",    "cwe": "CWE-327", "cvss": 7.5,
                 "tier": "always", "fortify": None,
                 "desc": "crypt() — uses DES (56-bit) — trivially breakable"},
    "getpass":  {"cat": "InfoLeak",      "cwe": "CWE-200", "cvss": 4.0,
                 "tier": "always", "fortify": None,
                 "desc": "getpass() — obsolete, may echo passwords on some terminals"},
    "inet_ntoa":{"cat": "BufferOverflow","cwe": "CWE-120", "cvss": 5.0,
                 "tier": "always", "fortify": None,
                 "desc": "inet_ntoa() — not thread-safe, uses static buffer"},
    "alloca":   {"cat": "BufferOverflow", "cwe": "CWE-787", "cvss": 7.5,
                 "tier": "always", "fortify": None,
                 "desc": "alloca() — stack allocation with no overflow protection; large allocs can smash stack"},
    "longjmp":  {"cat": "BypassCleanup",  "cwe": "CWE-456", "cvss": 5.5,
                 "tier": "context", "fortify": None,
                 "desc": "longjmp() — bypasses cleanup/destructors, can leak resources or corrupt state"},

    # ─── CONTEXT-DEPENDENT (dangerous if user data reaches the call) ──────────
    "strcpy":   {"cat": "BufferOverflow",  "cwe": "CWE-120", "cvss": 8.1,
                 "tier": "context", "fortify": "__strcpy_chk",
                 "desc": "Unchecked string copy — potential stack overflow"},
    "strcat":   {"cat": "BufferOverflow",  "cwe": "CWE-120", "cvss": 7.5,
                 "tier": "context", "fortify": "__strcat_chk",
                 "desc": "Unchecked string concatenation — heap/stack overflow"},
    "sprintf":  {"cat": "BufferOverflow",  "cwe": "CWE-134", "cvss": 7.5,
                 "tier": "context", "fortify": "__sprintf_chk",
                 "desc": "Unchecked sprintf — format/buffer overflow"},
    "vsprintf": {"cat": "BufferOverflow",  "cwe": "CWE-134", "cvss": 7.5,
                 "tier": "context", "fortify": "__vsprintf_chk",
                 "desc": "Unchecked vsprintf — format/buffer overflow"},
    "scanf":    {"cat": "BufferOverflow",  "cwe": "CWE-120", "cvss": 8.1,
                 "tier": "context", "fortify": "__isoc99_scanf",
                 "desc": "Unchecked scanf input — stack overflow"},
    "sscanf":   {"cat": "BufferOverflow",  "cwe": "CWE-120", "cvss": 7.5,
                 "tier": "context", "fortify": "__isoc99_sscanf",
                 "desc": "Unchecked sscanf — buffer overflow"},
    "read":     {"cat": "BufferOverflow",  "cwe": "CWE-122", "cvss": 7.5,
                 "tier": "context", "fortify": "__read_chk",
                 "desc": "read() without size validation — heap/stack overflow"},
    "fread":    {"cat": "BufferOverflow",  "cwe": "CWE-122", "cvss": 7.2,
                 "tier": "context", "fortify": "__fread_chk",
                 "desc": "fread() without bounds check — heap overflow"},
    "recv":     {"cat": "BufferOverflow",  "cwe": "CWE-122", "cvss": 9.1,
                 "tier": "context", "fortify": "__recv_chk",
                 "desc": "Network recv() without size validation — heap overflow"},
    "recvfrom": {"cat": "BufferOverflow",  "cwe": "CWE-122", "cvss": 9.1,
                 "tier": "context", "fortify": "__recvfrom_chk",
                 "desc": "recvfrom() — network buffer overflow if size unchecked"},
    "memcpy":   {"cat": "BufferOverflow",  "cwe": "CWE-122", "cvss": 7.5,
                 "tier": "context", "fortify": "__memcpy_chk",
                 "desc": "memcpy without destination size check"},
    "memmove":  {"cat": "BufferOverflow",  "cwe": "CWE-122", "cvss": 7.2,
                 "tier": "context", "fortify": "__memmove_chk",
                 "desc": "memmove without destination size check"},
    "memset":   {"cat": "BufferOverflow",  "cwe": "CWE-122", "cvss": 6.5,
                 "tier": "context", "fortify": "__memset_chk",
                 "desc": "memset — potential overflow if count exceeds destination"},
    # Format string — context-dependent
    "printf":   {"cat": "FormatString",    "cwe": "CWE-134", "cvss": 9.8,
                 "tier": "context", "fortify": "__printf_chk",
                 "desc": "Uncontrolled format string — memory read/write primitive"},
    "fprintf":  {"cat": "FormatString",    "cwe": "CWE-134", "cvss": 8.5,
                 "tier": "context", "fortify": "__fprintf_chk",
                 "desc": "Uncontrolled fprintf format string"},
    "snprintf": {"cat": "FormatString",    "cwe": "CWE-134", "cvss": 7.5,
                 "tier": "context", "fortify": "__snprintf_chk",
                 "desc": "Potential format string if format arg is user-controlled"},
    "dprintf":  {"cat": "FormatString",    "cwe": "CWE-134", "cvss": 8.5,
                 "tier": "context", "fortify": "__dprintf_chk",
                 "desc": "dprintf format string — potential arbitrary write"},
    "syslog":   {"cat": "FormatString",    "cwe": "CWE-134", "cvss": 7.2,
                 "tier": "context", "fortify": None,
                 "desc": "syslog format string — potential log injection / write"},
    # Memory management — context-dependent
    "malloc":   {"cat": "MemoryMgmt",      "cwe": "CWE-789", "cvss": 4.0,
                 "tier": "context", "fortify": None,
                 "desc": "malloc result unchecked — null dereference / heap misuse"},
    "free":     {"cat": "UseAfterFree",    "cwe": "CWE-416", "cvss": 5.5,
                 "tier": "context", "fortify": None,
                 "desc": "free() — potential double-free or use-after-free"},
    "realloc":  {"cat": "MemoryMgmt",      "cwe": "CWE-789", "cvss": 5.5,
                 "tier": "context", "fortify": None,
                 "desc": "realloc — size confusion / heap overflow possible"},
    "calloc":   {"cat": "MemoryMgmt",      "cwe": "CWE-789", "cvss": 4.0,
                 "tier": "context", "fortify": None,
                 "desc": "calloc — integer overflow in size × count"},
    # exec family — context-dependent (legitimate in many programs)
    "execve":   {"cat": "CommandInjection","cwe": "CWE-78",  "cvss": 8.1,
                 "tier": "context", "fortify": None,
                 "desc": "execve() — arbitrary code execution if args are user-tainted"},
    "execl":    {"cat": "CommandInjection","cwe": "CWE-78",  "cvss": 8.1,
                 "tier": "context", "fortify": None,
                 "desc": "execl() — command injection vector"},
    "execlp":   {"cat": "CommandInjection","cwe": "CWE-78",  "cvss": 7.5,
                 "tier": "context", "fortify": None,
                 "desc": "execlp() — PATH injection possible"},
    "execvp":   {"cat": "CommandInjection","cwe": "CWE-78",  "cvss": 7.5,
                 "tier": "context", "fortify": None,
                 "desc": "execvp() — PATH-based command injection"},
    # Dynamic loading — context-dependent
    "dlopen":   {"cat": "DynamicLoad",     "cwe": "CWE-114", "cvss": 6.5,
                 "tier": "context", "fortify": None,
                 "desc": "dlopen() — dynamic library injection if path user-controlled"},
    # Privilege — context-dependent (often legitimate privilege dropping)
    "setuid":   {"cat": "PrivEsc",         "cwe": "CWE-250", "cvss": 6.0,
                 "tier": "context", "fortify": None,
                 "desc": "setuid() — privilege manipulation; dangerous only if uid=0 or attacker-controlled arg"},
    "setgid":   {"cat": "PrivEsc",         "cwe": "CWE-250", "cvss": 5.5,
                 "tier": "context", "fortify": None,
                 "desc": "setgid() — privilege manipulation; verify argument before flagging"},
    "setgroups":{"cat": "PrivEsc",         "cwe": "CWE-250", "cvss": 6.0,
                 "tier": "context", "fortify": None,
                 "desc": "setgroups() — supplementary group manipulation"},
    "initgroups":{"cat": "PrivEsc",         "cwe": "CWE-250", "cvss": 5.5,
                 "tier": "context", "fortify": None,
                 "desc": "initgroups() — group membership manipulation"},
    # TOCTOU / race conditions
    "access":   {"cat": "TOCTOU",          "cwe": "CWE-367", "cvss": 6.5,
                 "tier": "context", "fortify": None,
                 "desc": "access() before open() — TOCTOU race condition"},
    "signal":   {"cat": "RaceCondition",   "cwe": "CWE-362", "cvss": 5.5,
                 "tier": "context", "fortify": None,
                 "desc": "signal() handler race condition — use sigaction() instead"},
    # Chroot / sandbox escape
    "chroot":   {"cat": "PrivEsc",         "cwe": "CWE-243", "cvss": 7.2,
                 "tier": "context", "fortify": None,
                 "desc": "chroot() without chdir() — possible filesystem escape"},
    # Tainted input
    "getenv":   {"cat": "TaintedInput",    "cwe": "CWE-526", "cvss": 5.0,
                 "tier": "context", "fortify": None,
                 "desc": "getenv() — environment variable is user-influenceable input"},
    "realpath": {"cat": "BufferOverflow",  "cwe": "CWE-120", "cvss": 5.5,
                 "tier": "context", "fortify": None,
                 "desc": "realpath() with insufficient buffer — path traversal / overflow"},
    # Network / socket functions in privileged context
    "bind":     {"cat": "NetworkExposed",  "cwe": "CWE-200", "cvss": 5.0,
                 "tier": "context", "fortify": None,
                 "desc": "bind() — network socket binding, attack surface in privileged binaries"},
    "connect":  {"cat": "NetworkExposed",  "cwe": "CWE-918", "cvss": 5.0,
                 "tier": "context", "fortify": None,
                 "desc": "connect() — outbound network connection, SSRF risk"},
    "accept":   {"cat": "NetworkExposed",  "cwe": "CWE-346", "cvss": 5.5,
                 "tier": "context", "fortify": None,
                 "desc": "accept() — accepts untrusted network input"},
    # Process control
    "fork":     {"cat": "RaceCondition",   "cwe": "CWE-362", "cvss": 4.0,
                 "tier": "context", "fortify": None,
                 "desc": "fork() — potential race conditions in signal handling between parent/child"},
    "ptrace":   {"cat": "PrivEsc",         "cwe": "CWE-250", "cvss": 7.0,
                 "tier": "context", "fortify": None,
                 "desc": "ptrace() — process inspection/injection, privilege escalation vector"},
    "prctl":    {"cat": "PrivEsc",         "cwe": "CWE-250", "cvss": 5.0,
                 "tier": "context", "fortify": None,
                 "desc": "prctl() — process control manipulation, can modify security settings"},
    "mprotect":{"cat": "MemoryMgmt",       "cwe": "CWE-272", "cvss": 6.5,
                 "tier": "context", "fortify": None,
                 "desc": "mprotect() — can make memory regions writable+executable (W^X violation)"},
    # Thread-unsafe functions
    "strerror": {"cat": "ThreadUnsafe",   "cwe": "CWE-366", "cvss": 3.5,
                 "tier": "safe_variant", "fortify": None,
                 "desc": "strerror() — not thread-safe, use strerror_r()"},
    "asctime":  {"cat": "ThreadUnsafe",   "cwe": "CWE-366", "cvss": 3.5,
                 "tier": "safe_variant", "fortify": None,
                 "desc": "asctime() — not thread-safe, uses static buffer"},
    "ctime":    {"cat": "ThreadUnsafe",   "cwe": "CWE-366", "cvss": 3.5,
                 "tier": "safe_variant", "fortify": None,
                 "desc": "ctime() — not thread-safe, uses static buffer"},
    "gmtime":   {"cat": "ThreadUnsafe",   "cwe": "CWE-366", "cvss": 3.5,
                 "tier": "safe_variant", "fortify": None,
                 "desc": "gmtime() — not thread-safe, use gmtime_r()"},
    "localtime":{"cat": "ThreadUnsafe",   "cwe": "CWE-366", "cvss": 3.5,
                 "tier": "safe_variant", "fortify": None,
                 "desc": "localtime() — not thread-safe, use localtime_r()"},
    "getlogin": {"cat": "InfoLeak",        "cwe": "CWE-200", "cvss": 3.5,
                 "tier": "safe_variant", "fortify": None,
                 "desc": "getlogin() — leaks username, not thread-safe"},
    "ttyname":  {"cat": "InfoLeak",        "cwe": "CWE-200", "cvss": 3.5,
                 "tier": "safe_variant", "fortify": None,
                 "desc": "ttyname() — leaks terminal name, not thread-safe"},

    # ─── SAFE VARIANT / INFORMATIONAL (low priority, don't inflate scores) ────
    "strncpy":  {"cat": "OffByOne",        "cwe": "CWE-193", "cvss": 3.5,
                 "tier": "safe_variant", "fortify": None,
                 "desc": "strncpy may not null-terminate — off-by-one (safer than strcpy)"},
    "strncat":  {"cat": "OffByOne",        "cwe": "CWE-193", "cvss": 3.5,
                 "tier": "safe_variant", "fortify": None,
                 "desc": "strncat misuse — off-by-one on null terminator (safer than strcat)"},
    "snprintf_safe": {"cat": "SafeVariant","cwe": "CWE-193", "cvss": 2.0,
                 "tier": "safe_variant", "fortify": None,
                 "desc": "snprintf with size limit — much safer than sprintf"},
    "strtok":   {"cat": "RaceCondition",   "cwe": "CWE-362", "cvss": 3.0,
                 "tier": "safe_variant", "fortify": None,
                 "desc": "strtok() — not thread-safe, use strtok_r()"},
    "rand":     {"cat": "WeakCrypto",       "cwe": "CWE-327", "cvss": 4.0,
                 "tier": "safe_variant", "fortify": None,
                 "desc": "rand() — weak PRNG, not cryptographically secure"},
    "srand":    {"cat": "WeakCrypto",       "cwe": "CWE-327", "cvss": 4.0,
                 "tier": "safe_variant", "fortify": None,
                 "desc": "srand() — weak seed for non-crypto PRNG"},
}

# ── Severity classification ────────────────────────────────────────────────────

SEVERITY_THRESHOLDS = [
    (9.0, "Critical"),
    (7.0, "High"),
    (4.0, "Medium"),
    (0.0, "Low"),
]

# ── FORTIFY _chk symbol mapping ────────────────────────────────────────────────

FORTIFY_MAP = {
    "__printf_chk":      "printf",
    "__fprintf_chk":     "fprintf",
    "__sprintf_chk":     "sprintf",
    "__snprintf_chk":   "snprintf",
    "__vprintf_chk":    "printf",
    "__vfprintf_chk":   "fprintf",
    "__vsprintf_chk":   "vsprintf",
    "__vsnprintf_chk":  "snprintf",
    "__dprintf_chk":    "dprintf",
    "__strcpy_chk":     "strcpy",
    "__strcat_chk":     "strcat",
    "__strncat_chk":    "strncat",
    "__strncpy_chk":    "strncpy",
    "__memcpy_chk":     "memcpy",
    "__memmove_chk":    "memmove",
    "__memset_chk":     "memset",
    "__read_chk":       "read",
    "__fread_chk":      "fread",
    "__recv_chk":       "recv",
    "__recvfrom_chk":   "recvfrom",
    "__gets_chk":       "gets",
    "__fgets_chk":      "fgets",
    "__wprintf_chk":    "wprintf",
    "__fwprintf_chk":   "fwprintf",
    "__swprintf_chk":   "swprintf",
}

# ── Mitigation hints ──────────────────────────────────────────────────────────

MITIGATIONS = {
    "gets":     "Replace gets() with fgets(buf, sizeof(buf), stdin).",
    "strcpy":   "Replace strcpy() with strlcpy() or snprintf().",
    "strcat":   "Replace strcat() with strlcat().",
    "sprintf":  "Replace sprintf() with snprintf() with explicit size.",
    "vsprintf": "Replace vsprintf() with vsnprintf().",
    "scanf":    "Use scanf(\"%Ns\", buf) with explicit field width N.",
    "sscanf":   "Validate input length before sscanf().",
    "printf":   "Always pass a literal format string: printf(\"%s\", user_input).",
    "fprintf":  "Always pass a literal format string to fprintf().",
    "snprintf": "Ensure format string is not user-controlled.",
    "dprintf":  "Ensure format string is a compile-time constant.",
    "syslog":   "Use syslog() with a format string literal, never user input.",
    "system":   "Avoid system(). Use execve() with a fixed path and validated args.",
    "popen":    "Validate and sanitise input before passing to popen().",
    "wordexp":  "Avoid wordexp() — use manual argument parsing to prevent shell expansion.",
    "execve":   "Validate all arguments; avoid user-controlled path components.",
    "execl":    "Validate all arguments; use absolute paths.",
    "execlp":   "Avoid PATH-based lookup — use execve() with absolute path.",
    "execvp":   "Avoid PATH-based lookup — use execve() with absolute path.",
    "recv":     "Always pass sizeof(buf) as the length argument to recv().",
    "recvfrom": "Validate buffer size before calling recvfrom().",
    "read":     "Validate buffer size before calling read().",
    "fread":    "Verify element count × size does not exceed destination buffer.",
    "memcpy":   "Check destination size before calling memcpy().",
    "memmove":  "Check destination size before calling memmove().",
    "memset":   "Verify count does not exceed destination size.",
    "free":     "Set pointer to NULL after free(); audit for double-free / UAF.",
    "malloc":   "Always check malloc() return value for NULL before use.",
    "realloc":  "Check realloc() return; handle NULL for new allocation.",
    "calloc":   "Validate nmemb × size does not overflow.",
    "dlopen":   "Use absolute paths and validate library origin before dlopen().",
    "setuid":   "Verify the argument: setuid(nobody) is privilege dropping, setuid(0) is escalation.",
    "setgid":   "Verify the argument: legitimate privilege dropping vs escalation.",
    "setgroups":"Verify supplementary groups are appropriate for privilege level.",
    "initgroups":"Verify group membership is appropriate.",
    "vfork":    "Replace vfork() with fork() to avoid parent-blocking and stack-sharing issues.",
    "signal":   "Use sigaction() instead of signal() for reliable signal handling.",
    "chroot":   "Always call chdir() immediately after chroot() and drop privileges.",
    "access":   "Avoid access()+open() pattern — use open() with O_NOFOLLOW instead.",
    "getenv":   "Validate and sanitise environment variable values before use.",
    "realpath": "Use realpath() with a sufficiently sized buffer (PATH_MAX).",
    "tempnam":  "Use mkstemp() or mkdtemp() with O_EXCL for safe temp file creation.",
    "mktemp":   "Use mkstemp() with O_EXCL instead of mktemp().",
    "crypt":    "Use crypt_r() or modern KDF (argon2, scrypt, bcrypt) instead of DES crypt().",
    "alloca":   "Replace alloca() with VLA (C99) or heap allocation; avoid unbounded stack alloc.",
    "longjmp":  "Avoid longjmp() over initialization frames; ensure cleanup paths are followed.",
    "bind":     "In privileged binaries, bind only to intended interfaces; verify socket options.",
    "connect":  "Validate destination address; guard against SSRF in privileged context.",
    "accept":   "Validate peer credentials; apply rate limiting; set socket timeouts.",
    "fork":     "Handle EAGAIN; reset signal handlers in child; close unnecessary fds.",
    "ptrace":   "Restrict ptrace via YAMA scope or seccomp; audit usage context.",
    "prctl":    "Audit prctl() calls for PR_SET_DUMPABLE, PR_SET_PTRACER, etc.",
    "mprotect": "Never make pages both writable and executable (W^X violation).",
    "strerror": "Use strerror_r() for thread-safe error messages.",
    "asctime":  "Use asctime_r() for thread-safe time conversion.",
    "ctime":    "Use ctime_r() for thread-safe time conversion.",
    "gmtime":   "Use gmtime_r() for thread-safe UTC time.",
    "localtime":"Use localtime_r() for thread-safe local time.",
    "getlogin": "Avoid getlogin() — use getpwuid(getuid()) instead.",
    "ttyname":  "Use ttyname_r() for thread-safe terminal name lookup.",
    "inet_ntoa":"Use inet_ntop() for thread-safe address conversion.",
    "strncpy":  "Ensure null-termination after strncpy(); consider strlcpy().",
    "strncat":  "Ensure null-termination after strncat(); consider strlcat().",
    "strtok":   "Use strtok_r() for thread-safe string tokenization.",
    "rand":     "Use arc4random() or getrandom() for cryptographic randomness.",
    "srand":    "Use arc4random_buf() or getrandom() for seeding.",
}

# ── Embedded mini CVE database ────────────────────────────────────────────────

KNOWN_CVES = {
    "glibc": [
        {"id": "CVE-2023-4911", "ver_range": ("<2.38",), "cvss": 7.8,
         "desc": "glibc lo_on_tunes buffer overflow (Fedora/Ubuntu)", "cwe": "CWE-120"},
        {"id": "CVE-2023-6246", "ver_range": ("<2.39",), "cvss": 9.8,
         "desc": "glibc __vsyslog_internal buffer overflow (syslog heap overflow)", "cwe": "CWE-120"},
        {"id": "CVE-2023-6779", "ver_range": ("<2.39",), "cvss": 7.5,
         "desc": "glibc OCSP nonce integer overflow", "cwe": "CWE-190"},
        {"id": "CVE-2023-6780", "ver_range": ("<2.39",), "cvss": 7.5,
         "desc": "glibc OCSP response length integer overflow", "cwe": "CWE-190"},
        {"id": "CVE-2024-2961", "ver_range": ("<2.40",), "cvss": 9.8,
         "desc": "glibc iconv ISO-2022-CN-EXT buffer overflow → RCE", "cwe": "CWE-120"},
        {"id": "CVE-2024-33577", "ver_range": ("<2.40",), "cvss": 9.8,
         "desc": "glibc stack-based buffer overflow in __vsyslog_internal()", "cwe": "CWE-121"},
        {"id": "CVE-2024-33578", "ver_range": ("<2.40",), "cvss": 8.8,
         "desc": "glibc heap-based buffer overflow in __vsyslog_internal()", "cwe": "CWE-122"},
        {"id": "CVE-2025-0314", "ver_range": ("<2.41",), "cvss": 8.1,
         "desc": "glibc fnmatch buffer overread", "cwe": "CWE-125"},
        {"id": "CVE-2025-1390", "ver_range": ("<2.41",), "cvss": 9.8,
         "desc": "glibc buffer overflow in assert() / __assert_fail", "cwe": "CWE-120"},
    ],
    "kernel": [
        {"id": "CVE-2024-21626", "ver_range": ("<6.7.2",), "cvss": 8.8,
         "desc": "kernel: runc container breakout via leaked file descriptor", "cwe": "CWE-732"},
        {"id": "CVE-2024-1086", "ver_range": ("<6.6.13",), "cvss": 7.8,
         "desc": "kernel: netfilter nf_tables double-free → LPE", "cwe": "CWE-416"},
        {"id": "CVE-2024-0193", "ver_range": ("<6.7.3",), "cvss": 7.0,
         "desc": "kernel: netfilter use-after-free in nft_verdict_init()", "cwe": "CWE-416"},
        {"id": "CVE-2024-41010", "ver_range": ("<6.10.3",), "cvss": 7.8,
         "desc": "kernel: mm: use-after-free in hugetlb vma lock", "cwe": "CWE-416"},
        {"id": "CVE-2024-46755", "ver_range": ("<6.11",), "cvss": 7.8,
         "desc": "kernel: HID: use-after-free in hid_hw_close()", "cwe": "CWE-416"},
        {"id": "CVE-2024-50164", "ver_range": ("<6.12",), "cvss": 7.8,
         "desc": "kernel: netfilter use-after-free in nft_parse_register", "cwe": "CWE-416"},
        {"id": "CVE-2025-21757", "ver_range": ("<6.13.2",), "cvss": 7.8,
         "desc": "kernel: netfilter use-after-free in nft_set_elem_flush()", "cwe": "CWE-416"},
        {"id": "CVE-2025-2247", "ver_range": ("<6.13.2",), "cvss": 7.1,
         "desc": "kernel: IPv6 HBH header use-after-free", "cwe": "CWE-416"},
        {"id": "CVE-2025-2498", "ver_range": ("<6.12.20",), "cvss": 7.0,
         "desc": "kernel: fs: NTFS stack buffer overflow", "cwe": "CWE-121"},
        {"id": "CVE-2025-2768", "ver_range": ("<6.13",), "cvss": 7.8,
         "desc": "kernel: i40e use-after-free in XSK buffer pool", "cwe": "CWE-416"},
    ],
    "openssl": [
        {"id": "CVE-2024-0727", "ver_range": ("<3.2.0",), "cvss": 5.3,
         "desc": "OpenSSL: DoS via PKCS7 bundle verification", "cwe": "CWE-400"},
        {"id": "CVE-2024-2511", "ver_range": ("<3.3.0",), "cvss": 5.3,
         "desc": "OpenSSL: unbounded 1-RTT DoS via connection stalls", "cwe": "CWE-400"},
        {"id": "CVE-2024-5535", "ver_range": ("<3.3.2",), "cvss": 9.8,
         "desc": "OpenSSL: Use-after-free in SSL object freeing", "cwe": "CWE-416"},
    ],
    "zlib": [
        {"id": "CVE-2022-37434", "ver_range": ("<1.2.13",), "cvss": 9.8,
         "desc": "zlib: heap-based buffer overflow in inflate()", "cwe": "CWE-122"},
    ],
}

# ── Linux capabilities known-dangerous mapping ─────────────────────────────────

DANGEROUS_CAPS = {
    "cap_setuid":     {"severity": "Critical", "cvss": 9.8, "desc": "Allows UID manipulation — full privilege escalation"},
    "cap_setgid":     {"severity": "High",     "cvss": 8.5, "desc": "Allows GID manipulation — group privilege escalation"},
    "cap_sys_admin":  {"severity": "Critical", "cvss": 9.8, "desc": "Near-root capability — mount, namespace, many privops"},
    "cap_sys_ptrace": {"severity": "High",      "cvss": 8.8, "desc": "Can inspect/modify any process memory — credential theft"},
    "cap_dac_override":{"severity": "High",     "cvss": 7.5, "desc": "Bypasses file permission checks"},
    "cap_dac_read_search":{"severity": "Medium", "cvss": 5.5, "desc": "Bypasses file read/search permission checks"},
    "cap_net_admin":  {"severity": "High",      "cvss": 7.5, "desc": "Network configuration — interface/routing/firewall manipulation"},
    "cap_net_raw":    {"severity": "Medium",     "cvss": 6.5, "desc": "Raw socket access — packet sniffing/spoofing"},
    "cap_sys_module":  {"severity": "Critical",  "cvss": 9.8, "desc": "Load kernel modules — arbitrary kernel code execution"},
    "cap_sys_chroot":  {"severity": "Medium",    "cvss": 5.0, "desc": "Chroot capability — potential sandbox escape"},
    "cap_sys_resource":{"severity": "Medium",    "cvss": 5.5, "desc": "Override resource limits — DoS potential"},
    "cap_linux_immutable":{"severity": "High",   "cvss": 7.0, "desc": "Can set immutable file attribute"},
    "cap_ipc_lock":   {"severity": "Low",        "cvss": 3.5, "desc": "Can lock memory — DoS potential"},
    "cap_kill":       {"severity": "Medium",     "cvss": 5.0, "desc": "Can signal any process"},
    "cap_sys_boot":   {"severity": "Critical",   "cvss": 9.8, "desc": "Can reboot the system"},
    "cap_sys_time":   {"severity": "Medium",     "cvss": 5.0, "desc": "Can manipulate system clock"},
    "cap_audit_control":{"severity": "High",     "cvss": 7.0, "desc": "Can manipulate audit logs"},
    "cap_mknod":      {"severity": "Medium",     "cvss": 5.5, "desc": "Can create device files — potential raw disk access"},
}